# Generated by Django 2.2.16 on 2020-11-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppersona', '0003_auto_20201101_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='usuario',
        ),
    ]
