# Generated by Django 2.2.16 on 2020-11-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppersona', '0004_remove_persona_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rut',
            field=models.TextField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
