# Generated by Django 2.2.16 on 2020-11-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppersona', '0005_persona_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/images/no-img.jpg', upload_to='apppersona')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
