# Generated by Django 2.2.16 on 2020-11-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppersona', '0006_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
