# Generated by Django 2.2.16 on 2020-11-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppersona', '0010_auto_20201102_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
