# Generated by Django 2.2.16 on 2020-11-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppersona', '0011_auto_20201102_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
