# Generated by Django 2.2.16 on 2020-11-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppersona', '0013_contactos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(max_length=30),
        ),
    ]
