# Generated by Django 2.2.16 on 2020-11-20 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apppersona', '0014_auto_20201109_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
